### ISSUE TITLE
VS Web Essentials 2017 - Toolbar Not Visible In Browser

### ISSUE THREAD

**Issue by mlorbetske** [madskristensen/WebEssentials2017#12]
_From @AronGrzywaczewski on April 30, 2017 9:37_

VS Web Essentials 2017 has failed to add the toolbar to the internet browser when debugging. Is there a fix for that or has the toolbar been removed from the VS Web Essentials 2017?

_Copied from original issue: aspnet/Tooling#1033_

**Comment by madskristensen** [comment]
It was removed for several reasons. 

1. It interfered too much with the DOM of the running page
2. It didn't work when the various features were split out into their own extension
3. I build this [Chrome extension](https://chrome.google.com/webstore/detail/web-essentials/mghdcdlpcdiodelbplncnodiiadljhhk) to replace it

**Comment by AronGrzywaczewski** [comment]
That's great, thanks Mads

I just wanted to clarify this for everyone who is having the same problem. After installing Web Essentials 2017 and the extension in the Chrome browser:  https://chrome.google.com/webstore/detail/web-essentials/mghdcdlpcdiodelbplncnodiiadljhhk you will also have to install additional addon in Visual Studio in order to work in design mode or to inspect the elements of the website called Browser Link Inspector: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.BrowserLinkInspector2017
